<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Learning Journey Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #111;
        }

        h2 {
            margin-bottom: 10px;
        }

        h3 {
            margin: 14px 0 6px;
            font-size: 13px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        th, td {
            border: 1px solid #999;
            padding: 5px;
        }

        th {
            background: #f0f0f0;
            text-align: center;
        }

        .section {
            margin-bottom: 18px;
        }

        .badge {
            font-size: 9px;
            padding: 2px 5px;
            border-radius: 4px;
            display: inline-block;
        }

        .green { background: #dcfce7; }
        .yellow { background: #fef9c3; }
        .red { background: #fee2e2; }
    </style>
</head>
<body>

<h2>Learning Journey Report</h2>

{{-- ================= EMPLOYEE INFO ================= --}}
<div class="section">
    <h3>Employee Information</h3>
    <table>
        <tr>
            <td><strong>Employee ID</strong></td>
            <td>{{ $employee->employee_id }}</td>
            <td><strong>Name</strong></td>
            <td>{{ $employee->name }}</td>
        </tr>
        <tr>
            <td><strong>Store</strong></td>
            <td>{{ $employee->store->name ?? '-' }}</td>
            <td><strong>Job</strong></td>
            <td>{{ $employee->job->name ?? '-' }}</td>
        </tr>
    </table>
</div>

{{-- ================= INTRODUCTION ================= --}}
<div class="section">
    <h3>Introduction Assessment</h3>

    @if($introduction)
    <table>
        <thead>
            <tr>
                <th>Assessment</th>
                <th>Analytic</th>
                <th>Business</th>
                <th>Leadership</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>FGD</td>
                <td>{{ $introduction->fgd_analytic_score ?? '-' }}</td>
                <td>{{ $introduction->fgd_business_score ?? '-' }}</td>
                <td>{{ $introduction->fgd_leadership_score ?? '-' }}</td>
            </tr>
            <tr>
                <td>Interview</td>
                <td>{{ $introduction->interview_analytic_score ?? '-' }}</td>
                <td>{{ $introduction->interview_business_score ?? '-' }}</td>
                <td>{{ $introduction->interview_leadership_score ?? '-' }}</td>
            </tr>
        </tbody>
    </table>

    <p><strong>Recommendation:</strong> {{ $introduction->rekomendasi ?? '-' }}</p>
    <p><strong>FGD Note:</strong> {{ $introduction->fgd_note ?? '-' }}</p>
    <p><strong>Interview Note:</strong> {{ $introduction->interview_note ?? '-' }}</p>

    <table>
        <tr>
            <td><strong>PIC</strong></td>
            <td colspan="3">{{ $introduction->pic ?? '-' }}</td>
        </tr>
    </table>
    @else
        <p>No introduction data</p>
    @endif
</div>

{{-- ================= ONBOARDING ================= --}}
<div class="section">
    <h3>Onboarding Checklist (6 Months)</h3>

    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Completion (%)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($onboardingData as $index => $percent)
            <tr>
                <td>Month {{ $index + 1 }}</td>
                <td>{{ $percent }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($isAutoGenerated)
        <p><em>Auto generated onboarding checklist</em></p>
    @endif
</div>

{{-- ================= DEVELOPMENT ================= --}}
<div class="section">
    <h3>Development & Training</h3>

    @if($development)
    <table>
        <tr><td>Supervisory Skill</td><td>{{ $development->rso_supervisory_skill }}</td></tr>
        <tr><td>Retail Salesmanship</td><td>{{ $development->rso_retail_salesmanship }}</td></tr>
        <tr><td>Customer Service Loyalty</td><td>{{ $development->rso_customer_service_loyalty }}</td></tr>
        <tr><td>Product Merchandising</td><td>{{ $development->rso_product_merchandising }}</td></tr>
        <tr><td>Visual Merchandising</td><td>{{ $development->rso_visual_merchandising }}</td></tr>
        <tr><td>Retail Store Promotion</td><td>{{ $development->rso_retail_store_promotion }}</td></tr>
        <tr><td>Financial Perspective</td><td>{{ $development->rso_store_financial_perspective }}</td></tr>
        <tr><td>General Strategy</td><td>{{ $development->rso_store_general_checkup_strategy }}</td></tr>
    </table>

    <p>
        <strong>Learning Hours:</strong> {{ $development->learning_hours }} |
        <strong>NGECAS:</strong> {{ $development->nilai_ngecas }}
    </p>

    <p>
        <strong>Compulsory:</strong> {{ $development->compulsory_training }} |
        <strong>Optional:</strong> {{ $development->optional_training }}
    </p>

    <p><strong>Development Program:</strong> {{ $development->development_program ?? '-' }}</p>
    @else
        <p>No development data</p>
    @endif
</div>

{{-- ================= MENTORING ================= --}}
<div class="section">
    <h3>Mentoring Records</h3>

    @if($mentoring->count())
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Mentor</th>
                <th>Store</th>
                <th>Notes</th>
                <th>HR Notes</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($mentoring as $m)
            <tr>
                <td>{{ $m->created_at?->format('d M Y') }}</td>
                <td>{{ $m->mentor_name }}</td>
                <td>{{ $m->store->name ?? '-' }}</td>
                <td>{{ $m->notes }}</td>
                <td>{{ $m->notes_hr }}</td>
                <td>{{ ucfirst($m->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <p>
        <strong>Total Mentoring:</strong> {{ $mentoring->count() }} |
        <strong>Verified:</strong> {{ $mentoring->where('status','verified')->count() }}
    </p>
    @else
        <p>No mentoring records</p>
    @endif
</div>

{{-- ================= KPI ================= --}}
<div class="section">
    <h3>Performance (KPI)</h3>

    @if($evaluation)
    <table>
        <tr>
            <th>Aspect</th>
            <th>June</th>
            <th>December</th>
            <th>Last Year June</th>
            <th>Last Year December</th>
        </tr>
        <tr>
            <td>Total KPI</td>
            <td>{{ $evaluation->kpi_june ?? '-' }}</td>
            <td>{{ $evaluation->kpi_december ?? '-' }}</td>
            <td>{{ $evaluation->last_year_kpi_june ?? '-' }}</td>
            <td>{{ $evaluation->last_year_kpi_december ?? '-' }}</td>
        </tr>
    </table>

    <p><strong>Assessment Link:</strong> {{ $evaluation->assessment_link ?? '-' }}</p>
    @else
        <p>No KPI data</p>
    @endif
</div>

</body>
</html>
