<?php

namespace App\Http\Controllers\Sales;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Employee;
use App\Models\Introduction;
use App\Models\OnboardingChecklist;
use App\Models\Mentoring;
use App\Models\EmployeeTrainingScore;
use App\Models\EmployeeEvaluation;
use App\Models\User;

class SalesReportController extends Controller
{
    public function show()
    {
        $user = Auth::user();

        // 🔑 Cari employee berdasarkan employee_id (email = employee_id)
        $employee = Employee::where('employee_id', $user->email)->firstOrFail();

        $checklists = OnboardingChecklist::where('employee_id', $employee->employee_id)
            ->orderBy('month')
            ->orderBy('week')
            ->get()
            ->groupBy('month');

        $isAutoGenerated = $checklists->has(0);

        $onboardingData = collect(range(1, 6))->map(function ($month) use ($checklists, $isAutoGenerated) {
            if ($isAutoGenerated) return 100;
            if (!isset($checklists[$month])) return 0;

            $approvedWeeks = $checklists[$month]
                ->where('status', 'approved')
                ->count();

            return ($approvedWeeks / 4) * 100;
        });

        return view('sales.report.show', [
            'employee'       => $employee->load(['store', 'job', 'region', 'section']),
            'introduction'   => Introduction::where('nik', $employee->employee_id)->first(),
            'checklists'     => $checklists,
            'onboardingData' => $onboardingData,
            'isAutoGenerated'=> $isAutoGenerated,
            'mentoring'      => Mentoring::where('employee_id', $employee->employee_id)->get(),
            'development'    => EmployeeTrainingScore::where('employee_id', $employee->employee_id)->first(),
            'evaluation'     => EmployeeEvaluation::where('employee_id', $employee->employee_id)->first(),
            'userAccount' => User::where('email', (string)$employee->employee_id)->first(),
        ]);
    }
}
