<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use App\Models\Introduction;
use App\Models\OnboardingChecklist;
use App\Models\Mentoring;
use App\Models\EmployeeTrainingScore;
use App\Models\EmployeeEvaluation;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Barryvdh\DomPDF\Facade\Pdf;

class EmployeeReportController extends Controller
{
    /**
     * VIEW REPORT (WEB)
     */
    public function show(Employee $employee)
    {
    $checklists = OnboardingChecklist::where('employee_id', $employee->employee_id)
        ->orderBy('month')
        ->orderBy('week')
        ->get()
        ->groupBy('month');

    // CEK AUTO GENERATED (MONTH 0)
    $isAutoGenerated = $checklists->has(0);

    // HITUNG ONBOARDING DATA
    $onboardingData = collect(range(1, 6))->map(function ($month) use ($checklists, $isAutoGenerated) {

        // KALAU AUTO GENERATED → FULL
        if ($isAutoGenerated) {
            return 100;
        }

        if (!isset($checklists[$month])) {
            return 0;
        }

        $totalWeeks = 4;
        $approvedWeeks = $checklists[$month]
            ->where('status', 'approved')
            ->count();

        return ($approvedWeeks / $totalWeeks) * 100;
    });


        return view('admin.employee-report.show', [
            'employee'        => $employee->load(['store', 'job']),
            'introduction'    => Introduction::where('nik', $employee->employee_id)->first(),
            'checklists'      => $checklists,
            'onboardingData'  => $onboardingData,
            'isAutoGenerated'  => $isAutoGenerated,
            'mentoring'       => Mentoring::where('employee_id', $employee->employee_id)->get(),
            'development'     => EmployeeTrainingScore::where('employee_id', $employee->employee_id)->first(),
            'evaluation'      => EmployeeEvaluation::where('employee_id', $employee->employee_id)->first(),
            'userAccount' => User::where('email', (string)$employee->employee_id)->first(),
        ]);
    }

    /**
     * DOWNLOAD PDF
     */
    public function pdf(Employee $employee)
    {
        $checklists = OnboardingChecklist::where('employee_id', $employee->employee_id)
            ->orderBy('month')
            ->orderBy('week')
            ->get()
            ->groupBy('month');

        // CEK AUTO GENERATED
        $isAutoGenerated = $checklists->has(0);

        // HITUNG ONBOARDING DATA (SAMA PERSIS SEPERTI SHOW)
        $onboardingData = collect(range(1, 6))->map(function ($month) use ($checklists, $isAutoGenerated) {

            if ($isAutoGenerated) {
                return 100;
            }

            if (!isset($checklists[$month])) {
                return 0;
            }

            $totalWeeks = 4;
            $approvedWeeks = $checklists[$month]
                ->where('status', 'approved')
                ->count();

            return ($approvedWeeks / $totalWeeks) * 100;
        });

        $data = [
            'employee'        => $employee->load(['store', 'job']),
            'introduction'    => Introduction::where('nik', $employee->employee_id)->first(),
            'checklists'      => $checklists,
            'onboardingData'  => $onboardingData,   // ✅ INI YANG KURANG
            'isAutoGenerated' => $isAutoGenerated,  // ✅ INI JUGA DIPAKAI
            'mentoring'       => Mentoring::where('employee_id', $employee->employee_id)->get(),
            'development'     => EmployeeTrainingScore::where('employee_id', $employee->employee_id)->first(),
            'evaluation'      => EmployeeEvaluation::where('employee_id', $employee->employee_id)->first(),
        ];

        $pdf = Pdf::loadView('admin.employee-report.pdf', $data)
            ->setPaper('a4', 'portrait');

        return $pdf->download(
            'Learning-Journey-' . $employee->employee_id . '.pdf'
        );
    }

    public function resetPassword($employee_id)
    {
        $user = User::where('email', $employee_id)->firstOrFail();

        $user->update([
            'password' => Hash::make('12345678')
        ]);

        return back()->with('success', 'Password berhasil direset ke default.');
    }
} 
